# Execute a job manually
name: Manual Execution

on:
  workflow_dispatch:
    
jobs:
  execute-job-manual:
    name: Execute Job manual
    runs-on: ubuntu-latest

    steps:
      #clone the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # install node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Intalação do Mocha
      - name: instalar Mocha
        run: npm install mocha

      # Run the tests
      - name: Run tests
        run: npx mocha tests/trabalho-final.js

      # Upload the results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/results.html      

