# Execute a job manually
name: Manual Execution

on:
  workflow_dispatch:
    
jobs:
  execute-job-manual:
    name: Execute Job manual
    runs-on: ubuntu-latest

    steps:
      #clone the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # install node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Intalação do Mocha
      - name: instalar Mocha e mochawesome
        run: |
          npm install mocha
          npm install mochawesome

      - name: Run tests and generate HTML report
        run: npx mocha tests/trabalho-final.js --reporter mochawesome --reporter-options reportDir=tests,reportFilename=results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/

      - name: Exibir instrução para visualização do artefato
        run: echo "Após a execução, acesse a aba 'Actions' do GitHub, selecione o workflow executado e faça o download do artefato 'test-results' para visualizar o relatório HTML dos testes."

